name: Deploy via snowcli

on: [push]

env:
  PYTHON_VERSION: '3.8'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Install snowcli'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install snowflake-cli-labs

    - name: 'Create snowsql config'
      shell: bash
      run: |
        cp tmp_config.toml config
        echo "password =${{ secrets.SNOWCLI_PW }}" >> config
        cat config

    - name: 'Deploy the streamlit app'
      shell: bash
      run: |
        snow streamlit deploy
